apiVersion: 1

datasources:
  - name: WARPXM Benchmarks
    type: frser-sqlite-datasource
    access: proxy
    uid: warpxm-benchmarks
    isDefault: false
    editable: true
    jsonData:
      path: __BENCHMARKS_DB_PATH__
